import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

const inter = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Menu",
  description: "Generated by Deep Net Soft Solutions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-white bg-black`}>
        {children}
      </body>
    </html>
  );
}
